{% set name = "mpifx" %}
{% set version = "1.5" %}
{% set build = 0 %}
{% set mpi = mpi or "nompi" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dftbplus/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 3801cbd6134b30f403b59346b40ff5bfb47ebe125892cf483e78b477c20b1b02

build:
  number: {{ build }}
  skip: true  # [win]

  {% set mpi_prefix = "mpi_" + mpi %}
  string: {{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}

  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }} {{ mpi_prefix }}_*

requirements:
  build:
    - {{ compiler('c') }}  # [osx]
    - {{ compiler('fortran') }}
    - cmake
    - ninja
    - fypp
    - {{ mpi }}  # [mpi == "openmpi" and build_platform != target_platform]
  host:
    - {{ mpi }}
  run:
    - {{ mpi }}

test:
  requires:
    - pkg-config
  commands:
    - pkg-config {{ name }} --modversion
    - test -f $PREFIX/lib/libmpifx${SHLIB_EXT}

about:
  home: https://github.com/dftbplus/{{ name }}
  license: BSD-2-Clause
  license_family: BSD
  license_file:
    - LICENSE
  summary: Modern Fortran Interface for MPI
  doc_url: https://dftbplus.github.io/{{ name }}/api/

extra:
  recipe-maintainers:
    - aradi
    - awvwgk
    - bhourahine
